export const GROUPS = [
  {
    id: 1,
    title: "Длинное предлинное длиннючее название прихода",
    date: "2017-06-29 12:09:33",
    quantity: 23,
    description: "Продукта",
    products: [
      {
        id: "1",
        serialNumber: "SN-12.3456789",
        isNew: 1,
        photo: "/images/products/monitors/product.webp",
        title: "Product 1",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "Свободен",
        group: "Длинное предлинное длиннючее название группы",
        fullName: null,
        parish: "Длинное предлинное длиннючее название прихода",
      },
      {
        id: "2",
        serialNumber: "SN-12.3456789",
        isNew: 0,
        photo: "/images/products/monitors/product.webp",
        title: "Інтерактивна панель Promethean ActivPanel LX 75 з модулем OPS-A",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "Свободен",
        group: "Длинное предлинное длиннючее название группы",
        fullName: "John Smith",
        parish: "Длинное предлинное длиннючее название прихода",
      },
      {
        id: "3",
        serialNumber: "SN-12.3456789",
        isNew: 0,
        photo: "/images/products/monitors/product.webp",
        title: "Інтерактивна панель Promethean ActivPanel LX 75 з модулем OPS-A",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "В ремонте",
        group: "Длинное предлинное длиннючее название группы",
        fullName: null,
        parish: "Длинное предлинное длиннючее название прихода",
      },
    ],
  },

  {
    id: 2,
    title: "Длинное предлинное длиннючее название прихода",
    date: "2017-06-29 12:09:33",
    quantity: 23,
    description: "Продукта",
    products: [
      {
        id: "1",
        serialNumber: "SN-12.3456789",
        isNew: 1,
        photo: "/images/products/monitors/product.webp",
        title: "Product 1",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "В наличии",
        group: "Длинное предлинное длиннючее название группы",
        fullName: null,
        parish: "Длинное предлинное длиннючее название прихода",
      },
      {
        id: "2",
        serialNumber: "SN-12.3456789",
        isNew: 0,
        photo: "/images/products/monitors/product.webp",
        title: "Інтерактивна панель Promethean ActivPanel LX 75 з модулем OPS-A",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "В ремонте",
        group: "Длинное предлинное длиннючее название группы",
        fullName: "John Smith",
        parish: "Длинное предлинное длиннючее название прихода",
      },
      {
        id: "3",
        serialNumber: "SN-12.3456789",
        isNew: 0,
        photo: "/images/products/monitors/product.webp",
        title: "Інтерактивна панель Promethean ActivPanel LX 75 з модулем OPS-A",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "Свободен",
        group: "Длинное предлинное длиннючее название группы",
        fullName: null,
        parish: "Длинное предлинное длиннючее название прихода",
      },
    ],
  },

  {
    id: 3,
    title: "Длинное предлинное длиннючее название прихода",
    date: "2017-06-29 12:09:33",
    quantity: 23,
    description: "Продукта",
    products: [
      {
        id: "1",
        serialNumber: "SN-12.3456789",
        isNew: 1,
        photo: "/images/products/monitors/product.webp",
        title: "Product 1",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "Свободен",
        group: "Длинное предлинное длиннючее название группы",
        fullName: null,
        parish: "Длинное предлинное длиннючее название прихода",
      },
      {
        id: "2",
        serialNumber: "SN-12.3456789",
        isNew: 0,
        photo: "/images/products/monitors/product.webp",
        title: "Інтерактивна панель Promethean ActivPanel LX 75 з модулем OPS-A",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "В ремонте",
        group: "Длинное предлинное длиннючее название группы",
        fullName: "John Smith",
        parish: "Длинное предлинное длиннючее название прихода",
      },
      {
        id: "3",
        serialNumber: "SN-12.3456789",
        isNew: 0,
        photo: "/images/products/monitors/product.webp",
        title: "Інтерактивна панель Promethean ActivPanel LX 75 з модулем OPS-A",
        type: "monitors",
        specification: "Specification 1",
        guarantee: {
          start: "2017-06-29 12:09:33",
          end: "2017-06-29 12:09:33",
        },
        price: [
          { value: 100, symbol: "USD", isDefault: 0 },
          { value: 2600, symbol: "UAH", isDefault: 1 },
        ],
        order: 1,
        date: "2017-06-29 12:09:33",
        status: "В ремонте",
        group: "Длинное предлинное длиннючее название группы",
        fullName: null,
        parish: "Длинное предлинное длиннючее название прихода",
      },
    ],
  },
];
